name: 🚀 Deploy pruebas
on: workflow_dispatch

jobs:
  compile-front-on-pruebas:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 104.198.134.0
          port: 22
          username: prohab
          password: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          local-dir: ./dist/
          server-dir: /mnt/data/aplicaciones/Prueba/git-test/
          dangerous-clean-slate: true