name: 🚀 Deploy pruebas
on: workflow_dispatch

jobs:
  upload-front-on-pruebas:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
  
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 📂 Upload models
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          server: 104.198.134.0
          port: 22
          username: prohab
          ssh_private_key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          local_path: ./application/models/*
          remote_path: /mnt/data/aplicaciones/Prueba/beneficiosmaderasback/models/
          delete_remote_files: true

      - name: 📂 Upload controllers
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          server: 104.198.134.0
          port: 22
          username: prohab
          ssh_private_key: ${{ secrets.SFTP_SSH_PRIVATE_KEY }}
          local_path: ./application/controllers/*
          remote_path: /mnt/data/aplicaciones/Prueba/beneficiosmaderasback/controllers/
          delete_remote_files: true
